from __future__ import annotations

import os
import re
import subprocess
import tempfile
from typing import Any, Dict, List, Set

import gradio as gr
import torch
from peft import PeftModel
from transformers import AutoModelForCausalLM, AutoTokenizer

# --- Configuration ---
BASE_MODEL: str = "Qwen/Qwen2.5-Coder-7B-Instruct"
ADAPTER_PATH: str = "./training_results/seed_42/final_adapter"

# --- Model Initialization ---
print("Loading tokenizer and model...")
tokenizer: Any = AutoTokenizer.from_pretrained(BASE_MODEL, use_fast=True, trust_remote_code=True)

base_model: Any = AutoModelForCausalLM.from_pretrained(
    BASE_MODEL,
    device_map="auto",
    torch_dtype=torch.bfloat16,
    attn_implementation="sdpa",
)

# Load the trained adapter
try:
    model: Any = PeftModel.from_pretrained(base_model, ADAPTER_PATH)
    print(f"Successfully loaded Proposed model adapter from {ADAPTER_PATH}")
except Exception as e:
    print(f"Error loading adapter, falling back to base model: {e}")
    model = base_model

model.eval()


# --- Core Functions ---

def extract_rust_code_single(text: str) -> str:
    """
    Extracts the Rust code block from a Markdown-formatted string.

    Args:
        text (str): The raw text generated by the LLM.

    Returns:
        str: The extracted Rust code, or the original text if no block is found.
    """
    pattern: str = r"```rust\s+(.*?)\s+```"
    match: re.Match | None = re.search(pattern, text, re.DOTALL | re.IGNORECASE)
    
    if match:
        return match.group(1).strip()
    return text.strip()


def convert_c_to_rust(user_message: str) -> str:
    """
    Translates C code to safe, idiomatic Rust using the fine-tuned LLM.

    Args:
        user_message (str): The C code to be translated.

    Returns:
        str: The generated and extracted Rust code.
    """
    system_prompt: str = """Convert the provided C program into safe, highly idiomatic stable Rust.

Rules for Translation:
1. Pure Safe Rust: Prefer 100% safe code. Use `unsafe` only if it is fundamentally impossible to achieve the behavior otherwise.
2. Native Types: Use standard Rust types (`i32`, `usize`, `str`, `String`, etc.). Strictly avoid FFI types (`c_int`, `c_char`, `c_void`, `*mut T`).
3. Idiomatic Memory & Ownership: Translate C-style manual memory management, pointer arithmetic, and raw arrays into Rust's ownership model (e.g., `Vec<T>`, `Box<T>`, slices, and iterators).
4. Error Handling: Refactor C-style error codes (e.g., returning -1 or NULL) into idiomatic `Result<T, E>` or `Option<T>` patterns.
5. Standard Library Only: Do not use any external crates unless they are commonly used. Rely almost entirely on `std`.
6. Zero Comments: Do not include any code comments in your output.
7. Inline Assembly: Replace __asm__ with safe equivalents or core::arch::asm!.
8. Identifier Preservation: Preserve original names but adjust to snake_case/PascalCase standards.

Output Format:
Respond STRICTLY with a single markdown code block tagged `rust`. Do not provide any conversational filler, explanations, or text before or after the code block. Your entire response must begin exactly with ```rust and end exactly with ```."""

    messages: List[Dict[str, str]] = [
        {"role": "system", "content": system_prompt},
        {"role": "user", "content": user_message}
    ]

    rendered_prompt: str = tokenizer.apply_chat_template(messages, tokenize=False, add_generation_prompt=True)
    inputs: Dict[str, torch.Tensor] = tokenizer(rendered_prompt, return_tensors="pt").to(model.device)

    with torch.inference_mode():
        outputs: torch.Tensor = model.generate(
            **inputs,
            max_new_tokens=1536,
            pad_token_id=tokenizer.pad_token_id,
            do_sample=False
        )

    prompt_lengths: int = inputs["input_ids"].shape[-1]
    generated_tokens: torch.Tensor = outputs[0, prompt_lengths:]
    pred_text: str = tokenizer.decode(generated_tokens, skip_special_tokens=True)

    return extract_rust_code_single(pred_text)


# --- Main Application Execution ---

def main() -> None:
    """Constructs and launches the Gradio UI."""
    with gr.Blocks(title="C to Rust Converter (Proposed Model)") as demo:
        gr.Markdown("# C to Rust Converter")
        gr.Markdown("Enter C code on the left to get Safe Rust on the right. Uses Qwen2.5-Coder fine-tuned adapter.")

        with gr.Row():
            with gr.Column():
                c_input = gr.Code(label="C Code", language="c")
                convert_btn = gr.Button("Convert to Rust", variant="primary")
            with gr.Column():
                rust_output = gr.Code(label="Rust Code", language="cpp", interactive=False)
                
        # Wiring the buttons
        convert_btn.click(fn=convert_c_to_rust, inputs=c_input, outputs=rust_output)
        
    demo.launch(debug=True)


if __name__ == "__main__":
    main()